import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Screen1 from './Componets/Sceen1'

import CollapsibleTable from './Componets/EmployeeTable'
import LoginUI from './Componets/LoginUI'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Screen1/>    */}
      <LoginUI/>
    </div>
  )
}
